import type { To } from "react-router";
import { runInAction } from "mobx";
import type { ProsemirrorData } from "@linear/common/models/ProsemirrorHelper";
import { notReachable } from "@linear/common/errors/UnreachableCaseError";
import type { DraftData } from "@linear/common/models/Draft";
import { schema } from "@linear/editor/schema";
import { editorDocTextContent } from "@linear/editor/utils";
import { Feature } from "#Features";
import type { AgentSession } from "#models/AgentSession";
import { ClientError } from "#models/graphQL/Errors";
import { Issue } from "#models/Issue";
import { ClientModel, ManyToOne, Property, LazyManyToOne, Computed } from "#models/base/Decorators";
import { DeletableModel } from "#models/base/Model";
import { JSONSerializer } from "#models/serialization/Serialization";
import { Project } from "#models/Project";
import { Comment, type CommentParentModel } from "#models/Comment";
import { User } from "#models/User";
import { LazyReference, type LazyValue } from "#models/hydration/Lazy";
import { ProjectUpdate } from "#models/ProjectUpdate";
import {
  agentSessionPath,
  commentPath,
  initiativeActivityPath,
  initiativeUpdateDraftPath,
  issuePath,
  projectUpdateDraftPath,
  projectUpdatesPath,
  reviewChangesPath,
  reviewCommentPath,
  reviewPath,
  updateOnUpdatesPagePath,
} from "#utils/urls";
import { Initiative } from "#models/Initiative";
import { InitiativeUpdate } from "#models/InitiativeUpdate";
import { PullRequest } from "#models/PullRequest";
import { PullRequestComment } from "#models/PullRequestComment";
import type { CustomHistoryState } from "#typings/custom-history-state";
import { Post } from "./Post";
import { Team } from "./Team";

/**
 * Type of the parent model of a draft.
 */
export type DraftParentModel =
  | Project
  | ProjectUpdate
  | Issue
  | Comment
  | Post
  | Initiative
  | InitiativeUpdate
  | PullRequest
  | PullRequestComment
  | Team;

/**
 * A model representing a draft.
 */
@ClientModel("Draft")
export class Draft extends DeletableModel {
  /** The user that created the draft. */
  @ManyToOne(() => User, "drafts", { nullable: false, optional: false, persistence: "createOnly" })
  public user: User;

  /** Whether the draft is autogenerated. */
  @Property({ persistence: "none", default: false })
  public isAutogenerated: boolean;

  /** Whether the draft was ported from a local draft. Only set when the draft is ported from a local draft. */
  @Property({ persistence: "createOnly", default: false })
  public wasLocalDraft: boolean;

  @Property({ default: {} })
  public data: DraftData;

  @Property()
  public anchor?: string;

  /** The associated issue if the draft is a root-level comment. */
  @LazyManyToOne(() => Issue, "draftComments", {
    optional: true,
    nullable: false,
    indexed: true,
    cascadeHydration: true,
    persistence: "createOnly",
  })
  public issue?: LazyReference<Issue>;

  /** The associated team if the draft is a post. */
  @LazyManyToOne(() => Team, "draftPosts", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createAndUpdate",
  })
  public team?: LazyReference<Team>;

  /** The associated project if the draft is a project update. */
  @LazyManyToOne(() => Project, "draftProjectUpdatesOrComments", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createAndUpdate",
  })
  public project?: LazyReference<Project>;

  /** The associated project update if the draft is a comment on a project update. */
  @LazyManyToOne(() => ProjectUpdate, "draftComments", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createOnly",
  })
  public projectUpdate?: LazyReference<ProjectUpdate>;

  /** The associated initiative if the draft is an initiative update. */
  @LazyManyToOne(() => Initiative, "draftInitiativeUpdatesOrComments", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createAndUpdate",
  })
  public initiative?: LazyReference<Initiative>;

  /** The associated initiative update if the draft is a comment on an initiative update. */
  @LazyManyToOne(() => InitiativeUpdate, "draftComments", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createOnly",
  })
  public initiativeUpdate?: LazyReference<InitiativeUpdate>;

  /** The post that this draft is associated with. */
  @LazyManyToOne(() => Post, "draftComments", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createOnly",
  })
  public post?: LazyReference<Post>;

  /** The associated comment if the draft is a reply to a comment. */
  @LazyManyToOne(() => Comment, "draftReplies", {
    optional: true,
    nullable: false,
    indexed: true,
    cascadeHydration: true,
    persistence: "createOnly",
  })
  public parentComment?: LazyReference<Comment>;

  /** The pull request that this draft is associated with. */
  @LazyManyToOne(() => PullRequest, "draftComments", {
    optional: true,
    nullable: false,
    indexed: true,
    persistence: "createOnly",
  })
  public pullRequest?: LazyReference<PullRequest>;

  /** The associated pull request comment if the draft is a reply to a pull request comment. */
  @LazyManyToOne(() => PullRequestComment, "draftReplies", {
    optional: true,
    nullable: false,
    indexed: true,
    cascadeHydration: true,
    persistence: "createOnly",
  })
  public parentPullRequestComment?: LazyReference<PullRequestComment>;

  /** The content of the comment in Prosemirror document. */
  @Property({ serializer: JSONSerializer, default: {} })
  public bodyData: ProsemirrorData;

  /** The parent model of the draft. */
  @Computed
  public get parentModel(): LazyValue<DraftParentModel> {
    return (
      this.issue?.value ??
      this.project?.value ??
      this.initiative?.value ??
      this.parentComment?.value ??
      this.projectUpdate?.value ??
      this.post?.value ??
      this.initiativeUpdate?.value ??
      this.pullRequest?.value ??
      this.parentPullRequestComment?.value ??
      this.team?.value
    );
  }

  /** Set the parent model of the draft. */
  public set parentModel(model: DraftParentModel) {
    switch (true) {
      case model instanceof Issue:
        this.issue = LazyReference.wrap(model);
        break;
      case model instanceof Project:
        this.project = LazyReference.wrap(model);
        break;
      case model instanceof Comment:
        this.parentComment = LazyReference.wrap(model);
        break;
      case model instanceof ProjectUpdate:
        this.projectUpdate = LazyReference.wrap(model);
        break;
      case model instanceof Post:
        this.post = LazyReference.wrap(model);
        break;
      case model instanceof Initiative:
        this.initiative = LazyReference.wrap(model);
        break;
      case model instanceof InitiativeUpdate:
        this.initiativeUpdate = LazyReference.wrap(model);
        break;
      case model instanceof PullRequest:
        this.pullRequest = LazyReference.wrap(model);
        break;
      case model instanceof PullRequestComment:
        this.parentPullRequestComment = LazyReference.wrap(model);
        break;
      case model instanceof Team:
        this.team = LazyReference.wrap(model);
        break;
      default:
        notReachable(model);
    }
  }

  /** Get the top-level model for the draft. */
  @Computed
  public get topLevelModel(): LazyValue<DraftParentModel | CommentParentModel> {
    const parentModel = this.parentModel;
    if (!parentModel) {
      return undefined;
    }
    // If it's a draft of a reply comment, go up a level to find the top-level parent
    return (parentModel instanceof Comment || parentModel instanceof PullRequestComment) && parentModel.isHydrated()
      ? parentModel.parentModel
      : parentModel;
  }

  /**
   * The agent session this draft was written in, if any. Agent chats persist their input against the session's root
   * comment, so a draft belongs to a session whenever its parent comment has one.
   */
  @Computed
  public get agentSession(): LazyValue<AgentSession> {
    const parentModel = this.parentModel;
    return parentModel instanceof Comment && parentModel.isHydrated() ? parentModel.agentSessions.first : undefined;
  }

  /** Whether this is a project update draft. */
  public get isProjectUpdateDraft(): boolean {
    return Boolean(this.data?.projectUpdate || (this.data?.generationMetadata && this.project?.value));
  }

  /** Whether this is an initiative update draft. */
  public get isInitiativeUpdateDraft(): boolean {
    return Boolean(this.data?.initiativeUpdate || (this.data?.generationMetadata && this.initiative));
  }

  /** Whether this is an update draft (project or initiative) as opposed to a comment draft. */
  public get isUpdateDraft(): boolean {
    return this.isProjectUpdateDraft || this.isInitiativeUpdateDraft;
  }

  /** Get the location for navigating to a draft. */
  @Computed
  public get location(): LazyValue<{ to: To; state: CustomHistoryState }> {
    let path = "";
    const state: CustomHistoryState = { draftId: this.id };
    const parentModel = this.parentModel;
    const topLevelModel = this.topLevelModel;

    if (!parentModel || !topLevelModel) {
      return undefined;
    }

    if (parentModel instanceof Comment && parentModel.isHydrated()) {
      const agentSession = this.agentSession;
      if (agentSession) {
        // The draft belongs to the agent chat, not to the comment thread behind it. Routing through the session's own
        // page lets its loader pick the surface the chat actually opens on (review sidebar, diff, or issue).
        path = agentSessionPath(agentSession);
      } else {
        path = commentPath(parentModel);
        state.highlightCommentThreadInput = true;
      }
    } else if (topLevelModel instanceof Issue) {
      path ||= issuePath(topLevelModel);
      state.highlightCommentComposer = true;
    } else if (topLevelModel instanceof Project) {
      const useUpdateDraftPage = this.isProjectUpdateDraft && Feature.isEnabled(Feature.entityActivity);
      path ||= useUpdateDraftPage ? projectUpdateDraftPath(topLevelModel) : projectUpdatesPath(topLevelModel);
      if (this.isProjectUpdateDraft) {
        if (!useUpdateDraftPage) {
          state.highlightUpdateComposer = true;
        }
      } else {
        state.highlightCommentComposer = true;
      }
    } else if (topLevelModel instanceof Initiative) {
      if (this.isInitiativeUpdateDraft && Feature.isEnabled(Feature.entityActivity)) {
        path ||= initiativeUpdateDraftPath(topLevelModel);
      } else {
        path ||= initiativeActivityPath(topLevelModel);
        if (this.isInitiativeUpdateDraft) {
          state.highlightUpdateComposer = true;
        } else {
          state.highlightCommentComposer = true;
        }
      }
    } else if (parentModel instanceof ProjectUpdate && parentModel.isHydrated()) {
      path ||= updateOnUpdatesPagePath(parentModel);
      // The draft targets a specific update's reply input (selected by the update hash), not the
      // page-level comment composer, so use the thread-input flag rather than highlightCommentComposer.
      state.highlightCommentThreadInput = true;
    } else if (parentModel instanceof InitiativeUpdate && parentModel.isHydrated()) {
      path ||= updateOnUpdatesPagePath(parentModel);
      state.highlightCommentThreadInput = true;
    } else if (parentModel instanceof PullRequest) {
      if (this.anchor) {
        // Inline code comment draft: open the code review view. `useDraftScrollNavigation` reads
        // `state.draftId` (set on line above) and scrolls to the draft once it's rendered.
        path ||= reviewChangesPath(parentModel);
      } else {
        path ||= reviewPath(parentModel);
        state.highlightCommentComposer = true;
      }
    } else if (parentModel instanceof PullRequestComment && parentModel.isHydrated()) {
      path ||= reviewCommentPath(parentModel);
      state.highlightCommentThreadInput = true;
    }

    const parsedUrl = new URL(path, window.location.origin);
    const pathname = parsedUrl.pathname;
    const search = parsedUrl.search;
    const hash = parsedUrl.hash;

    return {
      to: { pathname, search, hash },
      state,
    };
  }

  /** Plain text of the comment body. */
  @Computed
  public get bodyTextContent(): string {
    if (this.bodyData) {
      const doc = schema.nodeFromJSON(this.bodyData);
      return editorDocTextContent(doc);
    }
    return "";
  }

  /** Contains persistable content other than text. */
  @Computed
  public get bodyPersistable(): boolean {
    if (this.bodyData) {
      // Don't save drafts with less than 3 characters
      if (this.bodyTextContent.trim().length >= 3) {
        return true;
      }

      // But do save drafts with nodes that don't show up as characters
      const doc = schema.nodeFromJSON(this.bodyData);
      let persist = false;
      doc.nodesBetween(0, doc.content.size, node => {
        if (persist) {
          // No further recursion needed.
          return false;
        }

        persist = [
          "embed",
          "file",
          "figma",
          "iframe",
          "image",
          "video",
          "suggestion_userMentions",
          "issueMention",
          "entityMention",
          "entityEmbed",
          "documentMention",
          "emoji",
        ].includes(node.type.name);

        return;
      });

      return persist;
    }

    return false;
  }

  // - Static methods

  /** Whether the given model has a draft for the given user. */
  public static hasDraft(model: DraftParentModel, user: User, filter?: (draft: Draft) => boolean): boolean {
    return this.getDraftForModel(model, user, filter) !== undefined;
  }

  /**
   * Retrieve the draft entity for the given model and user. Archived drafts are excluded — a locally
   * archived draft is pending deletion, and rediscovering it would resurrect it and make later saves
   * fail against the already-deleted server row.
   */
  public static getDraftForModel(
    model: DraftParentModel,
    user: User,
    filter?: (draft: Draft) => boolean
  ): Draft | undefined {
    const collection = (() => {
      switch (true) {
        case model instanceof Issue:
          return model.draftComments;
        case model instanceof Project:
          return model.draftProjectUpdatesOrComments;
        case model instanceof ProjectUpdate:
          return model.draftComments;
        case model instanceof Comment:
          return model.draftReplies;
        case model instanceof InitiativeUpdate:
          return model.draftComments;
        case model instanceof Post:
          return model.draftComments;
        case model instanceof Initiative:
          return model.draftInitiativeUpdatesOrComments;
        case model instanceof PullRequest:
          return model.draftComments;
        case model instanceof PullRequestComment:
          return model.draftReplies;
        case model instanceof Team:
          return model.draftPosts;
        default:
          notReachable(model);
          return undefined;
      }
    })();

    return collection?.find(draft => !draft.isArchived && draft.user.id === user.id && (!filter || filter(draft)));
  }

  /**
   * Upserts a draft for the model with the provided data. Handles the case where a draft exists on the server
   * but hasn't been synced to the client yet by catching the conflict error and updating the synced draft.
   *
   * @param model the parent model to upsert the draft for.
   * @param user the user to upsert the draft for.
   * @param data the prosemirror data to set on the draft.
   * @param metadata optional metadata to merge into the draft.
   * @param filter optional predicate to find the existing draft (e.g. by anchor).
   * @param anchor optional anchor to stamp on a newly created draft, so it is found again by an anchor-scoped lookup.
   */
  public static async upsertDraftForModel(
    model: DraftParentModel,
    user: User,
    data: ProsemirrorData,
    metadata?: DraftData,
    filter?: (draft: Draft) => boolean,
    anchor?: string
  ): Promise<void> {
    const existingDraft = this.getDraftForModel(model, user, filter);
    if (existingDraft) {
      runInAction(() => {
        existingDraft.bodyData = data;
        existingDraft.data = { ...existingDraft.data, ...metadata };
      });
      await existingDraft.save().result();
      return;
    }

    // No local draft found - try to create one
    const newDraft = new Draft();
    runInAction(() => {
      newDraft.bodyData = data;
      newDraft.data = metadata ?? {};
      newDraft.user = user;
      newDraft.parentModel = model;
      if (anchor) {
        newDraft.anchor = anchor;
      }
    });

    try {
      // Suppress error toast so we can handle conflict gracefully
      await newDraft
        .save(true, {
          suppressErrorToast: true,
          transactionOptions: { preventUndo: true },
        })
        .result();
    } catch (error) {
      // Check if this is a "draft already exists" conflict
      if (error instanceof ClientError && error.message.includes("conflict on insert of Draft")) {
        // Draft may have synced while we were creating - try to find and update it
        const syncedDraft = this.getDraftForModel(model, user, filter);
        if (syncedDraft) {
          runInAction(() => {
            syncedDraft.bodyData = data;
            syncedDraft.data = { ...syncedDraft.data, ...metadata };
          });
          await syncedDraft.save().result();
          return;
        }
      }
      // Re-throw other errors to be handled by caller
      throw error;
    }
  }
}
